version: '3.7'
services:
  django:
    build: .
    volumes:
      - .:/app
    ports: 
      - "8000:8000"
    tty: true
    command: python django_app/manage.py runserver 0.0.0.0:8000
    networks:
      - net
  
  mysql:
    image: mysql:5.7
    volumes: 
      - .:/app
    expose:  
      - 3306
    environment:
      MYSQL_DATABASE: keyword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./data/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./data/mysql/conf.d:/etc/mysql/conf.d
      - ./data/mysql/db:/var/lib/mysql
    networks:
      - net
    
networks:
  net:
    